# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nuagenetworks.net" # the base hostname & protocol for your site
include: ['_static']

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: nuagenetworks
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "opensource @ nuagenetworks" # used by search engines

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "nuagenetworks"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "nuagenetworks"
  wordpress:
  youtube: "nuagenetworks"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: nuagenetworks

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate] 

